CREATE TABLE public.academicyear (
  academicyearid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title text NULL,
  courseid bigint NOT NULL,
  CONSTRAINT AcademicYears_pkey PRIMARY KEY (academicyearid),
  CONSTRAINT AcademicYears_AcdYearId_key UNIQUE (academicyearid),
  CONSTRAINT academicyear_courseid_fkey FOREIGN KEY (courseid) REFERENCES courses(courseid)
) TABLESPACE pg_default;

CREATE TABLE public.applications (
  applicationid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name text NULL,
  subtitle text NULL,
  imageurl text NULL,
  academicyearid bigint NOT NULL,
  courseid bigint NULL,
  documents text NULL,
  textinputfields text NULL,
  dropdownfields text NULL,
  CONSTRAINT Applications_pkey PRIMARY KEY (applicationid),
  CONSTRAINT Applications_ApplicationsId_key UNIQUE (applicationid),
  CONSTRAINT applications_academicyearid_fkey FOREIGN KEY (academicyearid) REFERENCES academicyear(academicyearid),
  CONSTRAINT applications_courseid_fkey FOREIGN KEY (courseid) REFERENCES courses(courseid)
) TABLESPACE pg_default;


CREATE TABLE public.courses (
  courseid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title character varying NOT NULL,
  subtitle character varying NULL,
  imageurl text NULL,
  CONSTRAINT Courses_pkey PRIMARY KEY (courseid),
  CONSTRAINT Courses_CourseId_key UNIQUE (courseid)
) TABLESPACE pg_default;

CREATE TABLE public.submittedforms (
  submittedformid bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  formid bigint NOT NULL,
  userid text NULL,
  documentsdata text NULL,
  textinputfieldsdata text NULL,
  submitted_date date NULL,
  modified_date date NULL,
  status text NULL,
  CONSTRAINT submittedforms_pkey PRIMARY KEY (submittedformid),
  CONSTRAINT submittedforms_formid_fkey FOREIGN KEY (formid) REFERENCES applications(applicationid)
) TABLESPACE pg_default;
