# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core backend and React frontend to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        env:
          POSTGRES_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build ./UMS.Backend.sln --configuration Release

      - name: dotnet publish
        run: dotnet publish ./UMS.Backend.sln -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for backend deployment
        uses: actions/upload-artifact@v4
        with:
          name: backend-artifact
          path: ${{env.DOTNET_ROOT}}/myapp

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: |
          cd ./UMS.API/UMS_Client
          npm install

      - name: Set environment variable for API base URL
        run: echo "VITE_API_BASE_URL=https://umsbackend.azurewebsites.net/api" >> .env

      - name: Build React app
        run: |
          cd ./UMS.API/UMS_Client
          npm run build

      - name: Upload artifact for frontend deployment
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifact
          path: ./UMS.API/UMS_Client/dist

  deploy:
    runs-on: ubuntu-latest
    needs: 
      - build-backend
      - build-frontend
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download backend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-artifact

      - name: Download frontend artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4CA782253EE548598EFB173F31609B4E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0634251C4FA84774A0D0C6C6C2275AF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C40329A861514D23B6C6E328FD670D5D }}

      - name: Deploy backend to Azure Web App
        id: deploy-backend
        uses: azure/webapps-deploy@v3
        env:
          POSTGRES_PASSWORD: ${{ secrets.MY_SECRET_PASSWORD }}
        with:
          app-name: 'umsbackend'
          slot-name: 'Production'
          package: .

      - name: Deploy frontend to Azure Web App
        id: deploy-frontend
        uses: azure/webapps-deploy@v3
        env:
          VITE_API_BASE_URL: 'https://umsbackend.azurewebsites.net/api'
        with:
          app-name: 'umsfrontend'
          slot-name: 'Production'
          package: UMS_Project/UMS_Web/UMS.API/UMS_Client/dist
